services:
  ros-jazzy:
    build:
      context: .
      args:
        ubuntu_ver: "24.04"
        ros2_ver: "jazzy"
    image: my/ros:jazzy
    container_name: ros-jazzy
    hostname: ros-jazzy
    working_dir: /home/ros2_ws
    tty: true
    volumes:
      - ./ros2_ws:/home/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
