services:
  ros_melodic:
    build:
      context: .
      args:
        ubuntu_ver: "18.04"
        ros1_ver: "melodic"
    image: myros:melodic
    container_name: ros-melodic
    hostname: ros-melodic
    working_dir: /home/ros1_ws
    tty: true
    volumes:
      - ./ros1_ws:/home/ros1_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
