services:
  ros-noetic-gpu:
    build:
      context: .
      args:
        base_image: "nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04"
    image: my/ros:gpu-noetic
    container_name: ros-noetic-gpu
    hostname: ros-noetic-gpu
    working_dir: /home/ros1_ws
    tty: true
    volumes:
      - ./ros1_ws:/home/ros1_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
